// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxRiDu3aOHESIs-meak7x9udD-dq0fd2U',
    appId: '1:987711529122:web:6cadb48749655c8fa7b7fb',
    messagingSenderId: '987711529122',
    projectId: 'medicines-ab51d',
    authDomain: 'medicines-ab51d.firebaseapp.com',
    storageBucket: 'medicines-ab51d.firebasestorage.app',
    measurementId: 'G-1STJ5WG5BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE6__IRHEeIRqcF0og583oyCfGzyuxJIA',
    appId: '1:987711529122:android:9d5fdcc8da6de74ca7b7fb',
    messagingSenderId: '987711529122',
    projectId: 'medicines-ab51d',
    storageBucket: 'medicines-ab51d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6BCIrIY0AOPGNMhznX49fvT7pmjyTgOQ',
    appId: '1:987711529122:ios:0d06c0aff3945e6ca7b7fb',
    messagingSenderId: '987711529122',
    projectId: 'medicines-ab51d',
    storageBucket: 'medicines-ab51d.firebasestorage.app',
    iosBundleId: 'com.example.medicen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6BCIrIY0AOPGNMhznX49fvT7pmjyTgOQ',
    appId: '1:987711529122:ios:0d06c0aff3945e6ca7b7fb',
    messagingSenderId: '987711529122',
    projectId: 'medicines-ab51d',
    storageBucket: 'medicines-ab51d.firebasestorage.app',
    iosBundleId: 'com.example.medicen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxRiDu3aOHESIs-meak7x9udD-dq0fd2U',
    appId: '1:987711529122:web:0449ca6fab1973efa7b7fb',
    messagingSenderId: '987711529122',
    projectId: 'medicines-ab51d',
    authDomain: 'medicines-ab51d.firebaseapp.com',
    storageBucket: 'medicines-ab51d.firebasestorage.app',
    measurementId: 'G-V1VNXW4KK4',
  );
}
